/**
 * Profils pays africains (49) — complète les 5 fiches manuelles :
 * Maroc, Algérie, Tunisie, Égypte, Sénégal.
 */

/** @typedef {import('./countryProfileBuilder.js').CountryProfile} CountryProfile */

/** @type {CountryProfile[]} */
export const AFRICA_COUNTRY_PROFILES = [
  // ── Afrique du Nord (hors fiches manuelles) ──
  {
    name: 'Libye',
    capital: 'Tripoli',
    airline: 'Libyan Airlines',
    transfer: 'Tripoli Airport Shuttle',
    carRental: 'Local car rental Libye',
    dmc: 'Local DMC Libye',
    tourismBoard: 'Libya Tourism',
    esim: 'Libyana eSIM',
    visa: 'Visa Libye — consulat',
    schengen: false,
  },
  {
    name: 'Mauritanie',
    capital: 'Nouakchott',
    airline: 'Mauritania Airlines',
    transfer: 'Nouakchott Airport Taxi',
    carRental: 'Europcar Mauritanie',
    dmc: 'Local DMC Mauritanie',
    tourismBoard: 'Visit Mauritania',
    esim: 'Mattel eSIM',
    visa: 'e-Visa Mauritanie',
    schengen: false,
  },

  // ── Afrique de l'Ouest ──
  {
    name: 'Bénin',
    capital: 'Porto-Novo',
    airline: 'Benin Airlines',
    transfer: 'Cotonou Airport Taxi',
    carRental: 'Budget Bénin',
    dmc: 'Local DMC Bénin',
    tourismBoard: 'Benin Tourism',
    esim: 'MTN Bénin eSIM',
    visa: 'e-Visa Bénin',
    schengen: false,
  },
  {
    name: 'Burkina Faso',
    capital: 'Ouagadougou',
    airline: 'Air Burkina',
    transfer: 'Ouagadougou Airport Taxi',
    carRental: 'Local car rental Burkina Faso',
    dmc: 'Local DMC Burkina Faso',
    tourismBoard: 'Burkina Faso Tourism',
    esim: 'Orange BF eSIM',
    visa: 'e-Visa Burkina Faso',
    schengen: false,
  },
  {
    name: 'Cap-Vert',
    capital: 'Praia',
    airline: 'TACV Cabo Verde Airlines',
    ferry: 'CV Interilhas',
    transfer: 'Praia Airport Shuttle',
    carRental: 'Budget Cap-Vert',
    dmc: 'Local DMC Cap-Vert',
    tourismBoard: 'Visit Cabo Verde',
    esim: 'Unitel CV eSIM',
    visa: 'Registre Cap-Vert',
    schengen: false,
  },
  {
    name: "Côte d'Ivoire",
    capital: 'Abidjan',
    airline: 'Air Côte d\'Ivoire',
    transfer: 'Abidjan Airport Shuttle',
    carRental: 'Europcar Côte d\'Ivoire',
    dmc: 'Local DMC Côte d\'Ivoire',
    tourismBoard: 'Côte d\'Ivoire Tourisme',
    insurance: 'NSIA Côte d\'Ivoire',
    esim: 'Orange CI eSIM',
    visa: 'e-Visa Côte d\'Ivoire',
    mice: 'Palais de la Culture Abidjan',
    schengen: false,
  },
  {
    name: 'Gambie',
    capital: 'Banjul',
    airline: 'Gambia Bird',
    ferry: 'Banjul-Barra Ferry',
    transfer: 'Banjul Airport Taxi',
    carRental: 'Local car rental Gambie',
    dmc: 'Local DMC Gambie',
    tourismBoard: 'Visit The Gambia',
    esim: 'Gamcel eSIM',
    visa: 'e-Visa Gambie',
    schengen: false,
  },
  {
    name: 'Ghana',
    capital: 'Accra',
    airline: 'Africa World Airlines',
    transfer: 'Accra Airport Shuttle',
    carRental: 'Europcar Ghana',
    dmc: 'Local DMC Ghana',
    tourismBoard: 'Visit Ghana',
    insurance: 'Enterprise Insurance Ghana',
    esim: 'MTN Ghana eSIM',
    visa: 'e-Visa Ghana',
    mice: 'Accra International Conference Centre',
    schengen: false,
  },
  {
    name: 'Guinée',
    capital: 'Conakry',
    airline: 'Guinea Airlines',
    transfer: 'Conakry Airport Taxi',
    carRental: 'Local car rental Guinée',
    dmc: 'Local DMC Guinée',
    tourismBoard: 'Guinée Tourism',
    esim: 'Orange Guinée eSIM',
    visa: 'e-Visa Guinée',
    schengen: false,
  },
  {
    name: 'Guinée-Bissau',
    capital: 'Bissau',
    airline: 'Guinea-Bissau Airlines',
    ferry: 'Bissau-Bubaque Ferry',
    transfer: 'Bissau Airport Taxi',
    carRental: 'Local car rental Guinée-Bissau',
    dmc: 'Local DMC Guinée-Bissau',
    tourismBoard: 'Guinée-Bissau Tourism',
    esim: 'Guinetel eSIM',
    visa: 'Visa Guinée-Bissau — consulat',
    schengen: false,
  },
  {
    name: 'Libéria',
    capital: 'Monrovia',
    airline: 'Lone Star Air',
    transfer: 'Monrovia Airport Taxi',
    carRental: 'Local car rental Libéria',
    dmc: 'Local DMC Libéria',
    tourismBoard: 'Liberia Tourism',
    esim: 'Lonestar Cell eSIM',
    visa: 'e-Visa Libéria',
    schengen: false,
  },
  {
    name: 'Mali',
    capital: 'Bamako',
    airline: 'Air Mali',
    transfer: 'Bamako Airport Taxi',
    carRental: 'Local car rental Mali',
    dmc: 'Local DMC Mali',
    tourismBoard: 'Mali Tourism',
    esim: 'Orange Mali eSIM',
    visa: 'e-Visa Mali',
    schengen: false,
  },
  {
    name: 'Niger',
    capital: 'Niamey',
    airline: 'Niger Airlines',
    transfer: 'Niamey Airport Taxi',
    carRental: 'Local car rental Niger',
    dmc: 'Local DMC Niger',
    tourismBoard: 'Niger Tourism',
    esim: 'Airtel Niger eSIM',
    visa: 'e-Visa Niger',
    schengen: false,
  },
  {
    name: 'Nigéria',
    capital: 'Abuja',
    airline: 'Air Peace',
    transfer: 'Lagos / Abuja Airport Shuttle',
    carRental: 'Europcar Nigéria',
    dmc: 'Local DMC Nigéria',
    tourismBoard: 'Nigeria Tourism',
    insurance: 'Leadway Assurance',
    esim: 'MTN Nigeria eSIM',
    visa: 'e-Visa Nigéria',
    mice: 'Eko Hotels Lagos',
    schengen: false,
  },
  {
    name: 'Sierra Leone',
    capital: 'Freetown',
    airline: 'Sierra Leone Airlines',
    ferry: 'Freetown-Lungi Ferry',
    transfer: 'Lungi Airport Water Taxi',
    carRental: 'Local car rental Sierra Leone',
    dmc: 'Local DMC Sierra Leone',
    tourismBoard: 'Sierra Leone Tourism',
    esim: 'Orange SL eSIM',
    visa: 'e-Visa Sierra Leone',
    schengen: false,
  },
  {
    name: 'Togo',
    capital: 'Lomé',
    airline: 'ASKY Airlines',
    transfer: 'Lomé Airport Taxi',
    carRental: 'Budget Togo',
    dmc: 'Local DMC Togo',
    tourismBoard: 'Togo Tourism',
    esim: 'Moov Togo eSIM',
    visa: 'e-Visa Togo',
    schengen: false,
  },

  // ── Afrique centrale ──
  {
    name: 'Angola',
    capital: 'Luanda',
    airline: 'TAAG Angola Airlines',
    transfer: 'Luanda Airport Shuttle',
    carRental: 'Europcar Angola',
    dmc: 'Local DMC Angola',
    tourismBoard: 'Angola Tourism',
    esim: 'Unitel Angola eSIM',
    visa: 'e-Visa Angola',
    schengen: false,
  },
  {
    name: 'Cameroun',
    capital: 'Yaoundé',
    airline: 'Camair-Co',
    transfer: 'Douala / Yaoundé Airport Taxi',
    carRental: 'Budget Cameroun',
    dmc: 'Local DMC Cameroun',
    tourismBoard: 'Cameroon Tourism',
    esim: 'MTN Cameroun eSIM',
    visa: 'e-Visa Cameroun',
    schengen: false,
  },
  {
    name: 'Congo',
    capital: 'Brazzaville',
    airline: 'Equatorial Congo Airlines',
    ferry: 'Congo River Ferry',
    transfer: 'Brazzaville Airport Taxi',
    carRental: 'Local car rental Congo',
    dmc: 'Local DMC Congo',
    tourismBoard: 'Congo Tourism',
    esim: 'MTN Congo eSIM',
    visa: 'e-Visa Congo',
    schengen: false,
  },
  {
    name: 'République démocratique du Congo',
    capital: 'Kinshasa',
    airline: 'Congo Airways',
    transfer: 'Kinshasa Airport Taxi',
    carRental: 'Local car rental RDC',
    dmc: 'Local DMC RDC',
    tourismBoard: 'Visit DRC',
    esim: 'Vodacom RDC eSIM',
    visa: 'e-Visa RDC',
    schengen: false,
  },
  {
    name: 'Gabon',
    capital: 'Libreville',
    airline: 'Afrijet',
    transfer: 'Libreville Airport Taxi',
    carRental: 'Budget Gabon',
    dmc: 'Local DMC Gabon',
    tourismBoard: 'Gabon Tourism',
    esim: 'Airtel Gabon eSIM',
    visa: 'e-Visa Gabon',
    schengen: false,
  },
  {
    name: 'Guinée équatoriale',
    capital: 'Malabo',
    airline: 'CEIBA Intercontinental',
    ferry: 'Malabo Ferry',
    transfer: 'Malabo Airport Taxi',
    carRental: 'Local car rental Guinée équatoriale',
    dmc: 'Local DMC Guinée équatoriale',
    tourismBoard: 'Equatorial Guinea Tourism',
    esim: 'GETESA eSIM',
    visa: 'Visa Guinée équatoriale — consulat',
    schengen: false,
  },
  {
    name: 'République centrafricaine',
    capital: 'Bangui',
    airline: 'Centrafrique Airlines',
    transfer: 'Bangui Airport Taxi',
    carRental: 'Local car rental RCA',
    dmc: 'Local DMC République centrafricaine',
    tourismBoard: 'RCA Tourism',
    esim: 'Telecel RCA eSIM',
    visa: 'Visa RCA — consulat',
    schengen: false,
  },
  {
    name: 'São Tomé-et-Príncipe',
    capital: 'São Tomé',
    airline: 'STP Airways',
    ferry: 'São Tomé Ferry',
    transfer: 'São Tomé Airport Taxi',
    carRental: 'Local car rental São Tomé',
    dmc: 'Local DMC São Tomé-et-Príncipe',
    tourismBoard: 'Visit São Tomé',
    esim: 'CST eSIM',
    visa: 'e-Visa São Tomé-et-Príncipe',
    schengen: false,
  },
  {
    name: 'Tchad',
    capital: 'N\'Djamena',
    airline: 'Tchadia Airlines',
    transfer: 'N\'Djamena Airport Taxi',
    carRental: 'Local car rental Tchad',
    dmc: 'Local DMC Tchad',
    tourismBoard: 'Chad Tourism',
    esim: 'Airtel Tchad eSIM',
    visa: 'e-Visa Tchad',
    schengen: false,
  },

  // ── Afrique de l'Est ──
  {
    name: 'Burundi',
    capital: 'Gitega',
    airline: 'Air Burundi',
    transfer: 'Bujumbura Airport Taxi',
    carRental: 'Local car rental Burundi',
    dmc: 'Local DMC Burundi',
    tourismBoard: 'Burundi Tourism',
    esim: 'Econet Burundi eSIM',
    visa: 'e-Visa Burundi',
    schengen: false,
  },
  {
    name: 'Comores',
    capital: 'Moroni',
    airline: 'Comores Aviation',
    ferry: 'Comores Inter-îles',
    transfer: 'Moroni Airport Taxi',
    carRental: 'Local car rental Comores',
    dmc: 'Local DMC Comores',
    tourismBoard: 'Comores Tourism',
    esim: 'Comores Telecom eSIM',
    visa: 'e-Visa Comores',
    schengen: false,
  },
  {
    name: 'Djibouti',
    capital: 'Djibouti',
    airline: 'Air Djibouti',
    ferry: 'Djibouti Ferry',
    transfer: 'Djibouti Airport Taxi',
    carRental: 'Budget Djibouti',
    dmc: 'Local DMC Djibouti',
    tourismBoard: 'Visit Djibouti',
    esim: 'Djibouti Telecom eSIM',
    visa: 'e-Visa Djibouti',
    schengen: false,
  },
  {
    name: 'Érythrée',
    capital: 'Asmara',
    airline: 'Eritrean Airlines',
    transfer: 'Asmara Airport Taxi',
    carRental: 'Local car rental Érythrée',
    dmc: 'Local DMC Érythrée',
    tourismBoard: 'Eritrea Tourism',
    esim: 'EriTel eSIM',
    visa: 'Visa Érythrée — consulat',
    schengen: false,
  },
  {
    name: 'Éthiopie',
    capital: 'Addis-Abeba',
    airline: 'Ethiopian Airlines',
    rail: 'Ethio-Djibouti Railway',
    transfer: 'Addis Ababa Bole Shuttle',
    carRental: 'Budget Éthiopie',
    dmc: 'Local DMC Éthiopie',
    tourismBoard: 'Ethiopia Tourism',
    insurance: 'Ethiopian Insurance',
    esim: 'Ethio Telecom eSIM',
    visa: 'e-Visa Éthiopie',
    mice: 'AU Conference Center Addis',
    schengen: false,
  },
  {
    name: 'Kenya',
    capital: 'Nairobi',
    airline: 'Kenya Airways',
    rail: 'Madaraka Express',
    transfer: 'Nairobi JKIA Shuttle',
    carRental: 'Europcar Kenya',
    dmc: 'Local DMC Kenya',
    tourismBoard: 'Magical Kenya',
    insurance: 'Jubilee Insurance',
    esim: 'Safaricom eSIM',
    visa: 'e-Visa Kenya',
    mice: 'KICC Nairobi',
    schengen: false,
  },
  {
    name: 'Madagascar',
    capital: 'Antananarivo',
    airline: 'Madagascar Airlines',
    ferry: 'Madagascar Ferries',
    transfer: 'Antananarivo Airport Taxi',
    carRental: 'Budget Madagascar',
    dmc: 'Local DMC Madagascar',
    tourismBoard: 'Madagascar Tourism',
    esim: 'Telma eSIM',
    visa: 'e-Visa Madagascar',
    schengen: false,
  },
  {
    name: 'Malawi',
    capital: 'Lilongwe',
    airline: 'Malawi Airlines',
    transfer: 'Lilongwe Airport Taxi',
    carRental: 'Local car rental Malawi',
    dmc: 'Local DMC Malawi',
    tourismBoard: 'Malawi Tourism',
    esim: 'Airtel Malawi eSIM',
    visa: 'e-Visa Malawi',
    schengen: false,
  },
  {
    name: 'Maurice',
    capital: 'Port-Louis',
    airline: 'Air Mauritius',
    ferry: 'Mauritius Catamaran',
    transfer: 'SSR Airport Shuttle',
    carRental: 'Europcar Maurice',
    dmc: 'Local DMC Maurice',
    tourismBoard: 'Mauritius Tourism',
    esim: 'my.t eSIM',
    visa: 'Mauritius Premium Visa',
    schengen: false,
  },
  {
    name: 'Mozambique',
    capital: 'Maputo',
    airline: 'LAM Mozambique',
    ferry: 'Maputo Ferry',
    transfer: 'Maputo Airport Taxi',
    carRental: 'Budget Mozambique',
    dmc: 'Local DMC Mozambique',
    tourismBoard: 'Mozambique Tourism',
    esim: 'Vodacom MZ eSIM',
    visa: 'e-Visa Mozambique',
    schengen: false,
  },
  {
    name: 'Ouganda',
    capital: 'Kampala',
    airline: 'Uganda Airlines',
    transfer: 'Entebbe Airport Shuttle',
    carRental: 'Budget Ouganda',
    dmc: 'Local DMC Ouganda',
    tourismBoard: 'Explore Uganda',
    esim: 'MTN Uganda eSIM',
    visa: 'e-Visa Ouganda',
    schengen: false,
  },
  {
    name: 'Rwanda',
    capital: 'Kigali',
    airline: 'RwandAir',
    transfer: 'Kigali Airport Shuttle',
    carRental: 'Europcar Rwanda',
    dmc: 'Local DMC Rwanda',
    tourismBoard: 'Visit Rwanda',
    insurance: 'Radiant Insurance',
    esim: 'MTN Rwanda eSIM',
    visa: 'e-Visa Rwanda',
    mice: 'Kigali Convention Centre',
    schengen: false,
  },
  {
    name: 'Seychelles',
    capital: 'Victoria',
    airline: 'Air Seychelles',
    ferry: 'Seychelles Ferries',
    transfer: 'Mahé Airport Shuttle',
    carRental: 'Budget Seychelles',
    dmc: 'Local DMC Seychelles',
    tourismBoard: 'Seychelles Tourism',
    esim: 'Cable & Wireless SC eSIM',
    visa: 'Travel Authorization Seychelles',
    schengen: false,
  },
  {
    name: 'Somalie',
    capital: 'Mogadiscio',
    airline: 'Daallo Airlines',
    transfer: 'Mogadishu Airport Taxi',
    carRental: 'Local car rental Somalie',
    dmc: 'Local DMC Somalie',
    tourismBoard: 'Somalia Tourism',
    esim: 'Hormuud eSIM',
    visa: 'Visa Somalie — consulat',
    schengen: false,
  },
  {
    name: 'Soudan',
    capital: 'Khartoum',
    airline: 'Sudan Airways',
    rail: 'Sudan Railways',
    transfer: 'Khartoum Airport Taxi',
    carRental: 'Local car rental Soudan',
    dmc: 'Local DMC Soudan',
    tourismBoard: 'Sudan Tourism',
    esim: 'Sudani eSIM',
    visa: 'e-Visa Soudan',
    schengen: false,
  },
  {
    name: 'Soudan du Sud',
    capital: 'Djouba',
    airline: 'South Sudan Airways',
    transfer: 'Juba Airport Taxi',
    carRental: 'Local car rental Soudan du Sud',
    dmc: 'Local DMC Soudan du Sud',
    tourismBoard: 'South Sudan Tourism',
    esim: 'MTN South Sudan eSIM',
    visa: 'e-Visa Soudan du Sud',
    schengen: false,
  },
  {
    name: 'Tanzanie',
    capital: 'Dodoma',
    airline: 'Air Tanzania',
    ferry: 'Azam Marine Ferry',
    transfer: 'Dar es Salaam / Zanzibar Shuttle',
    carRental: 'Budget Tanzanie',
    dmc: 'Local DMC Tanzanie',
    tourismBoard: 'Tanzania Tourism',
    esim: 'Vodacom TZ eSIM',
    visa: 'e-Visa Tanzanie',
    schengen: false,
  },

  // ── Afrique australe ──
  {
    name: 'Afrique du Sud',
    capital: 'Pretoria',
    airline: 'South African Airways',
    rail: 'Shosholoza Meyl',
    transfer: 'Gautrain Johannesburg',
    carRental: 'Europcar Afrique du Sud',
    dmc: 'Local DMC Afrique du Sud',
    tourismBoard: 'South African Tourism',
    insurance: 'Old Mutual',
    esim: 'Vodacom SA eSIM',
    visa: 'e-Visa Afrique du Sud',
    mice: 'Cape Town ICC',
    schengen: false,
  },
  {
    name: 'Botswana',
    capital: 'Gaborone',
    airline: 'Air Botswana',
    transfer: 'Gaborone Airport Taxi',
    carRental: 'Budget Botswana',
    dmc: 'Local DMC Botswana',
    tourismBoard: 'Botswana Tourism',
    esim: 'Orange Botswana eSIM',
    visa: 'e-Visa Botswana',
    schengen: false,
  },
  {
    name: 'Eswatini',
    capital: 'Mbabane',
    airline: 'Eswatini Air',
    transfer: 'Mbabane / Manzini Shuttle',
    carRental: 'Local car rental Eswatini',
    dmc: 'Local DMC Eswatini',
    tourismBoard: 'Eswatini Tourism',
    esim: 'Eswatini Mobile eSIM',
    visa: 'Visa Eswatini — consulat',
    schengen: false,
  },
  {
    name: 'Lesotho',
    capital: 'Maseru',
    airline: 'Maluti Sky',
    transfer: 'Maseru Airport Taxi',
    carRental: 'Local car rental Lesotho',
    dmc: 'Local DMC Lesotho',
    tourismBoard: 'Lesotho Tourism',
    esim: 'Econet Lesotho eSIM',
    visa: 'e-Visa Lesotho',
    schengen: false,
  },
  {
    name: 'Namibie',
    capital: 'Windhoek',
    airline: 'Air Namibia',
    transfer: 'Windhoek Hosea Kutako Shuttle',
    carRental: 'Europcar Namibie',
    dmc: 'Local DMC Namibie',
    tourismBoard: 'Namibia Tourism',
    esim: 'MTC Namibia eSIM',
    visa: 'e-Visa Namibie',
    schengen: false,
  },
  {
    name: 'Zambie',
    capital: 'Lusaka',
    airline: 'Zambia Airways',
    transfer: 'Lusaka Airport Taxi',
    carRental: 'Budget Zambie',
    dmc: 'Local DMC Zambie',
    tourismBoard: 'Zambia Tourism',
    esim: 'Airtel Zambia eSIM',
    visa: 'e-Visa Zambie',
    schengen: false,
  },
  {
    name: 'Zimbabwe',
    capital: 'Harare',
    airline: 'Air Zimbabwe',
    transfer: 'Harare Airport Taxi',
    carRental: 'Budget Zimbabwe',
    dmc: 'Local DMC Zimbabwe',
    tourismBoard: 'Zimbabwe Tourism',
    esim: 'Econet Zimbabwe eSIM',
    visa: 'e-Visa Zimbabwe',
    schengen: false,
  },
]

/** 54 pays africains — ordre d'affichage par sous-région. */
export const AFRICA_COUNTRY_NAMES = [
  'Maroc', 'Algérie', 'Tunisie', 'Libye', 'Mauritanie', 'Égypte',
  'Bénin', 'Burkina Faso', 'Cap-Vert', "Côte d'Ivoire", 'Gambie', 'Ghana',
  'Guinée', 'Guinée-Bissau', 'Libéria', 'Mali', 'Niger', 'Nigéria',
  'Sénégal', 'Sierra Leone', 'Togo',
  'Angola', 'Cameroun', 'Congo', 'République démocratique du Congo', 'Gabon',
  'Guinée équatoriale', 'République centrafricaine', 'São Tomé-et-Príncipe', 'Tchad',
  'Burundi', 'Comores', 'Djibouti', 'Érythrée', 'Éthiopie', 'Kenya',
  'Madagascar', 'Malawi', 'Maurice', 'Mozambique', 'Ouganda', 'Rwanda',
  'Seychelles', 'Somalie', 'Soudan', 'Soudan du Sud', 'Tanzanie',
  'Afrique du Sud', 'Botswana', 'Eswatini', 'Lesotho', 'Namibie', 'Zambie', 'Zimbabwe',
]
