/**
 * Profils pays compacts — UE, Golfe, Asie, Amérique latine, Afrique.
 * Les pays déjà détaillés manuellement dans providersData.js ne sont pas listés ici.
 */

import { AFRICA_COUNTRY_PROFILES } from './africaCountryProfiles.js'

/** @typedef {import('./countryProfileBuilder.js').CountryProfile} CountryProfile */

/** @type {CountryProfile[]} */
export const EU_COUNTRY_PROFILES = [
  {
    name: 'Allemagne',
    capital: 'Berlin',
    airline: 'Lufthansa',
    rail: 'Deutsche Bahn',
    carRental: 'Europcar Deutschland',
    transfer: 'FlixBus / DB Fernverkehr',
    ferry: 'Finnlines',
    dmc: 'Local DMC Allemagne',
    tourismBoard: 'German National Tourist Board',
    insurance: 'Allianz Deutschland',
    esim: 'Telekom eSIM',
    mice: 'Messe Frankfurt',
    schengen: true,
  },
  {
    name: 'Autriche',
    capital: 'Vienne',
    airline: 'Austrian Airlines',
    rail: 'ÖBB',
    carRental: 'Europcar Autriche',
    transfer: 'Vienna Airport Lines',
    dmc: 'Local DMC Autriche',
    tourismBoard: 'Österreich Werbung',
    insurance: 'UNIQA',
    esim: 'A1 eSIM',
    mice: 'Messe Wien',
    schengen: true,
  },
  {
    name: 'Bulgarie',
    capital: 'Sofia',
    airline: 'Bulgaria Air',
    rail: 'BDZ',
    carRental: 'Europcar Bulgarie',
    transfer: 'Sofia Airport Transfer',
    dmc: 'Local DMC Bulgarie',
    tourismBoard: 'Ministry of Tourism Bulgaria',
    insurance: 'Bulstrad',
    esim: 'A1 Bulgaria eSIM',
    schengen: true,
  },
  {
    name: 'Chypre',
    capital: 'Nicosie',
    airline: 'Cyprus Airways',
    transfer: 'Kapnos Airport Shuttle',
    dmc: 'Local DMC Chypre',
    tourismBoard: 'Visit Cyprus',
    insurance: 'Eurolife',
    esim: 'Cyta eSIM',
    schengen: true,
  },
  {
    name: 'Croatie',
    capital: 'Zagreb',
    airline: 'Croatia Airlines',
    rail: 'HŽ Putnički Prijevoz',
    ferry: 'Jadrolinija',
    carRental: 'Europcar Croatie',
    transfer: 'Pleso Prijevoz',
    dmc: 'Local DMC Croatie',
    tourismBoard: 'Croatian National Tourist Board',
    insurance: 'Croatia Osiguranje',
    esim: 'A1 Hrvatska eSIM',
    schengen: true,
  },
  {
    name: 'Danemark',
    capital: 'Copenhague',
    airline: 'SAS',
    rail: 'DSB',
    ferry: 'DFDS Copenhague',
    carRental: 'Europcar Danemark',
    transfer: 'Metro Copenhague',
    dmc: 'Local DMC Danemark',
    tourismBoard: 'Visit Denmark',
    insurance: 'Tryg',
    esim: 'TDC eSIM',
    schengen: true,
  },
  {
    name: 'Estonie',
    capital: 'Tallinn',
    airline: 'Nordica',
    rail: 'Elron',
    carRental: 'Europcar Estonie',
    transfer: 'Tallinn Airport Shuttle',
    dmc: 'Local DMC Estonie',
    tourismBoard: 'Visit Estonia',
    insurance: 'If P&C',
    esim: 'Telia eSIM',
    schengen: true,
  },
  {
    name: 'Finlande',
    capital: 'Helsinki',
    airline: 'Finnair',
    rail: 'VR',
    ferry: 'Viking Line',
    carRental: 'Europcar Finlande',
    transfer: 'Finnair City Bus',
    dmc: 'Local DMC Finlande',
    tourismBoard: 'Visit Finland',
    insurance: 'If Vahinko',
    esim: 'Elisa eSIM',
    schengen: true,
  },
  {
    name: 'Grèce',
    capital: 'Athènes',
    airline: 'Aegean Airlines',
    rail: 'OSE / TrainOSE',
    ferry: 'Blue Star Ferries',
    carRental: 'Europcar Grèce',
    transfer: 'X95 Athènes Express',
    dmc: 'Local DMC Grèce',
    tourismBoard: 'Visit Greece',
    insurance: 'Ethniki Asfalistiki',
    esim: 'Cosmote eSIM',
    schengen: true,
  },
  {
    name: 'Hongrie',
    capital: 'Budapest',
    airline: 'Wizz Air',
    rail: 'MÁV',
    carRental: 'Europcar Hongrie',
    transfer: 'BKK Budapest',
    dmc: 'Local DMC Hongrie',
    tourismBoard: 'Hungarian Tourism Agency',
    insurance: 'Groupama',
    esim: 'Telekom HU eSIM',
    schengen: true,
  },
  {
    name: 'Irlande',
    capital: 'Dublin',
    airline: 'Aer Lingus',
    rail: 'Irish Rail',
    ferry: 'Irish Ferries',
    carRental: 'Europcar Irlande',
    transfer: 'Dublin Express',
    dmc: 'Local DMC Irlande',
    tourismBoard: 'Tourism Ireland',
    insurance: 'Aviva Ireland',
    esim: 'Three Ireland eSIM',
    visa: 'Irish Immigration Service',
    schengen: false,
  },
  {
    name: 'Lettonie',
    capital: 'Riga',
    airline: 'airBaltic',
    rail: 'Latvijas dzelzceļš',
    carRental: 'Europcar Lettonie',
    transfer: 'Riga Airport Bus',
    dmc: 'Local DMC Lettonie',
    tourismBoard: 'Latvia Travel',
    insurance: 'Balta',
    esim: 'LMT eSIM',
    schengen: true,
  },
  {
    name: 'Lituanie',
    capital: 'Vilnius',
    airline: 'Ryanair Lituanie',
    rail: 'LTG Link',
    carRental: 'Europcar Lituanie',
    transfer: 'Vilnius Airport Express',
    dmc: 'Local DMC Lituanie',
    tourismBoard: 'Lithuania Travel',
    insurance: 'If Lietuva',
    esim: 'Telia LT eSIM',
    schengen: true,
  },
  {
    name: 'Luxembourg',
    capital: 'Luxembourg',
    airline: 'Luxair',
    rail: 'CFL',
    carRental: 'Europcar Luxembourg',
    transfer: 'Luxembourg Airport Shuttle',
    dmc: 'Local DMC Luxembourg',
    tourismBoard: 'Visit Luxembourg',
    insurance: 'Foyer Assurances',
    esim: 'POST eSIM',
    schengen: true,
  },
  {
    name: 'Malte',
    capital: 'La Valette',
    airline: 'Air Malta',
    ferry: 'Virtu Ferries',
    carRental: 'Europcar Malte',
    transfer: 'Malta Transfer',
    dmc: 'Local DMC Malte',
    tourismBoard: 'Visit Malta',
    insurance: 'Mapfre Malta',
    esim: 'GO eSIM',
    schengen: true,
  },
  {
    name: 'Pays-Bas',
    capital: 'Amsterdam',
    airline: 'KLM',
    rail: 'NS Nederland',
    ferry: 'Stena Line Holland',
    carRental: 'Europcar Pays-Bas',
    transfer: 'NS Schiphol Sprinter',
    dmc: 'Local DMC Pays-Bas',
    tourismBoard: 'Netherlands Board of Tourism',
    insurance: 'Achmea',
    esim: 'KPN eSIM',
    mice: 'RAI Amsterdam',
    schengen: true,
  },
  {
    name: 'Pologne',
    capital: 'Varsovie',
    airline: 'LOT Polish Airlines',
    rail: 'PKP Intercity',
    carRental: 'Europcar Pologne',
    transfer: 'Modlin Bus / ZTM',
    dmc: 'Local DMC Pologne',
    tourismBoard: 'Polish Tourism Organisation',
    insurance: 'PZU',
    esim: 'Orange Polska eSIM',
    schengen: true,
  },
  {
    name: 'République tchèque',
    capital: 'Prague',
    airline: 'Smartwings',
    rail: 'ČD',
    carRental: 'Europcar République tchèque',
    transfer: 'AE Prague Airport Express',
    dmc: 'Local DMC République tchèque',
    tourismBoard: 'Czech Tourism',
    insurance: 'Kooperativa',
    esim: 'O2 CZ eSIM',
    schengen: true,
  },
  {
    name: 'Roumanie',
    capital: 'Bucarest',
    airline: 'TAROM',
    rail: 'CFR Călători',
    carRental: 'Europcar Roumanie',
    transfer: 'STB Bucarest',
    dmc: 'Local DMC Roumanie',
    tourismBoard: 'Romania Tourism',
    insurance: 'Groupama RO',
    esim: 'Orange RO eSIM',
    schengen: true,
  },
  {
    name: 'Slovaquie',
    capital: 'Bratislava',
    airline: 'Smartwings Slovaquie',
    rail: 'ZSSK',
    carRental: 'Europcar Slovaquie',
    transfer: 'Bratislava Airport Bus',
    dmc: 'Local DMC Slovaquie',
    tourismBoard: 'Slovakia Travel',
    insurance: 'Allianz SK',
    esim: 'Orange SK eSIM',
    schengen: true,
  },
  {
    name: 'Slovénie',
    capital: 'Ljubljana',
    airline: 'Adria Airways',
    rail: 'SŽ',
    carRental: 'Europcar Slovénie',
    transfer: 'Ljubljana Airport Shuttle',
    dmc: 'Local DMC Slovénie',
    tourismBoard: 'Slovenia Tourism',
    insurance: 'Triglav',
    esim: 'Telekom SI eSIM',
    schengen: true,
  },
  {
    name: 'Suède',
    capital: 'Stockholm',
    airline: 'SAS',
    rail: 'SJ',
    ferry: 'Stena Line Suède',
    carRental: 'Europcar Suède',
    transfer: 'Flygbussarna',
    dmc: 'Local DMC Suède',
    tourismBoard: 'Visit Sweden',
    insurance: 'Folksam',
    esim: 'Telia SE eSIM',
    schengen: true,
  },
]

/** @type {CountryProfile[]} */
export const GULF_MENA_PROFILES = [
  {
    name: 'Arabie saoudite',
    capital: 'Riyad',
    airline: 'Saudia',
    transfer: 'SAPTCO / Careem',
    carRental: 'Budget Saudi',
    dmc: 'Saudi Tourism DMC',
    tourismBoard: 'Visit Saudi',
    insurance: 'Tawuniya',
    esim: 'STC eSIM',
    visa: 'e-Visa Arabie saoudite',
    mice: 'Riyadh Front Exhibition',
    schengen: false,
  },
  {
    name: 'Qatar',
    capital: 'Doha',
    airline: 'Qatar Airways',
    transfer: 'Karwa / Careem',
    carRental: 'Budget Qatar',
    dmc: 'Qatar Tourism DMC',
    tourismBoard: 'Visit Qatar',
    insurance: 'Qatar Insurance',
    esim: 'Ooredoo Qatar eSIM',
    visa: 'Hayya / e-Visa Qatar',
    mice: 'Qatar National Convention Centre',
    schengen: false,
  },
  {
    name: 'Koweït',
    capital: 'Koweït',
    airline: 'Kuwait Airways',
    transfer: 'KPTC Airport Shuttle',
    carRental: 'Budget Koweït',
    dmc: 'Local DMC Koweït',
    tourismBoard: 'Kuwait Tourism',
    insurance: 'Gulf Insurance',
    esim: 'Zain Koweït eSIM',
    visa: 'e-Visa Koweït',
    schengen: false,
  },
  {
    name: 'Bahreïn',
    capital: 'Manama',
    airline: 'Gulf Air',
    ferry: 'Bahrain Ferries',
    transfer: 'Bahrain Airport Taxi',
    carRental: 'Budget Bahreïn',
    dmc: 'Local DMC Bahreïn',
    tourismBoard: 'Bahrain Tourism',
    insurance: 'Solidarity Bahrain',
    esim: 'Batelco eSIM',
    visa: 'e-Visa Bahreïn',
    schengen: false,
  },
  {
    name: 'Oman',
    capital: 'Mascate',
    airline: 'Oman Air',
    transfer: 'Mwasalat',
    carRental: 'Europcar Oman',
    dmc: 'Local DMC Oman',
    tourismBoard: 'Experience Oman',
    insurance: 'Oman Insurance',
    esim: 'Omantel eSIM',
    visa: 'e-Visa Oman',
    schengen: false,
  },
  {
    name: 'Jordanie',
    capital: 'Amman',
    airline: 'Royal Jordanian',
    transfer: 'JETT Airport Shuttle',
    carRental: 'Europcar Jordanie',
    dmc: 'Local DMC Jordanie',
    tourismBoard: 'Visit Jordan',
    insurance: 'Arab Orient Insurance',
    esim: 'Zain Jordan eSIM',
    visa: 'e-Visa Jordanie',
    schengen: false,
  },
  {
    name: 'Liban',
    capital: 'Beyrouth',
    airline: 'Middle East Airlines',
    transfer: 'Taxi Beyrouth',
    carRental: 'Budget Liban',
    dmc: 'Local DMC Liban',
    tourismBoard: 'Lebanon Travel',
    insurance: 'Bankers Assurance',
    esim: 'Touch Liban eSIM',
    visa: 'Visa Liban — ambassade',
    schengen: false,
  },
  {
    name: 'Irak',
    capital: 'Bagdad',
    airline: 'Iraqi Airways',
    transfer: 'Baghdad Airport Transfer',
    carRental: 'Local car rental Irak',
    dmc: 'Local DMC Irak',
    tourismBoard: 'Iraq Tourism',
    insurance: 'Asia Insurance Irak',
    esim: 'Zain Irak eSIM',
    visa: 'Visa Irak — consulat',
    schengen: false,
  },
  {
    name: 'Iran',
    capital: 'Téhéran',
    airline: 'Iran Air',
    rail: 'RAI',
    transfer: 'Tehran Metro Airport',
    carRental: 'Local car rental Iran',
    dmc: 'Local DMC Iran',
    tourismBoard: 'Iran Tourism',
    insurance: 'Iran Insurance',
    esim: 'Irancell eSIM',
    visa: 'Visa Iran — ambassade',
    schengen: false,
  },
  {
    name: 'Palestine',
    capital: 'Ramallah',
    airline: 'Royal Jordanian',
    transfer: 'Taxi Cisjordanie',
    dmc: 'Local DMC Palestine',
    tourismBoard: 'Visit Palestine',
    insurance: 'National Insurance Palestine',
    esim: 'Jawwal eSIM',
    visa: 'Visa Palestine — via Jordanie',
    schengen: false,
  },
  {
    name: 'Yémen',
    capital: 'Aden',
    airline: 'Yemenia',
    transfer: 'Taxi Aden',
    dmc: 'Local DMC Yémen',
    tourismBoard: 'Yemen Tourism',
    esim: 'Yemen Mobile eSIM',
    visa: 'Visa Yémen — consulat',
    schengen: false,
  },
]

/** @type {CountryProfile[]} */
export const ASIA_PROFILES = [
  {
    name: 'Russie',
    capital: 'Moscou',
    airline: 'Aeroflot',
    rail: 'RZD',
    ferry: 'St Peter Line',
    carRental: 'Europcar Russie',
    transfer: 'Aeroexpress Moscou',
    dmc: 'Local DMC Russie',
    tourismBoard: 'Visit Russia',
    insurance: 'Ingosstrakh',
    esim: 'MTS eSIM',
    visa: 'Visa Russie — consulat',
    mice: 'Crocus Expo Moscou',
    schengen: false,
  },
  {
    name: 'Chine',
    capital: 'Pékin',
    airline: 'Air China',
    rail: 'China Railway',
    transfer: 'Airport Express Pékin',
    carRental: 'Europcar Chine',
    dmc: 'Local DMC Chine',
    tourismBoard: 'Visit China',
    insurance: 'PICC',
    esim: 'China Unicom eSIM',
    visa: 'Visa Chine — consulat',
    mice: 'National Convention Center Pékin',
    schengen: false,
  },
  {
    name: 'Japon',
    capital: 'Tokyo',
    airline: 'JAL',
    rail: 'JR East / Shinkansen',
    ferry: 'Japan Ferry',
    carRental: 'Nippon Rent-A-Car',
    transfer: 'Narita Express',
    dmc: 'Local DMC Japon',
    tourismBoard: 'JNTO',
    insurance: 'Sompo Japan',
    esim: 'SoftBank eSIM',
    visa: 'Visa Japon — consulat',
    mice: 'Tokyo Big Sight',
    schengen: false,
  },
  {
    name: 'Corée du Sud',
    capital: 'Séoul',
    airline: 'Korean Air',
    rail: 'KORAIL',
    transfer: 'AREX Séoul',
    carRental: 'Lotte Rent-A-Car',
    dmc: 'Local DMC Corée du Sud',
    tourismBoard: 'Korea Tourism',
    insurance: 'Samsung Fire',
    esim: 'SK Telecom eSIM',
    visa: 'K-ETA Corée du Sud',
    schengen: false,
  },
  {
    name: 'Inde',
    capital: 'New Delhi',
    airline: 'Air India',
    rail: 'Indian Railways',
    transfer: 'Delhi Airport Metro',
    carRental: 'Europcar Inde',
    dmc: 'Local DMC Inde',
    tourismBoard: 'Incredible India',
    insurance: 'ICICI Lombard',
    esim: 'Jio eSIM',
    visa: 'e-Visa Inde',
    mice: 'India Expo Mart',
    schengen: false,
  },
  {
    name: 'Thaïlande',
    capital: 'Bangkok',
    airline: 'Thai Airways',
    rail: 'State Railway of Thailand',
    ferry: 'Lomprayah',
    transfer: 'Airport Rail Link Bangkok',
    carRental: 'Budget Thaïlande',
    dmc: 'Local DMC Thaïlande',
    tourismBoard: 'Tourism Authority of Thailand',
    insurance: 'Bangkok Insurance',
    esim: 'AIS eSIM',
    visa: 'e-Visa Thaïlande',
    schengen: false,
  },
  {
    name: 'Vietnam',
    capital: 'Hanoï',
    airline: 'Vietnam Airlines',
    rail: 'Vietnam Railways',
    ferry: 'Superdong',
    transfer: 'Noi Bai Airport Shuttle',
    carRental: 'Budget Vietnam',
    dmc: 'Local DMC Vietnam',
    tourismBoard: 'Vietnam Tourism',
    insurance: 'Bao Viet',
    esim: 'Viettel eSIM',
    visa: 'e-Visa Vietnam',
    schengen: false,
  },
  {
    name: 'Indonésie',
    capital: 'Jakarta',
    airline: 'Garuda Indonesia',
    ferry: 'Pelni Ferries',
    transfer: 'Soekarno-Hatta Airport Train',
    carRental: 'Avis Indonésie',
    dmc: 'Local DMC Indonésie',
    tourismBoard: 'Wonderful Indonesia',
    insurance: 'Allianz Indonésie',
    esim: 'Telkomsel eSIM',
    visa: 'e-Visa Indonésie',
    schengen: false,
  },
  {
    name: 'Malaisie',
    capital: 'Kuala Lumpur',
    airline: 'Malaysia Airlines',
    rail: 'KTMB',
    transfer: 'KLIA Ekspres',
    carRental: 'Europcar Malaisie',
    dmc: 'Local DMC Malaisie',
    tourismBoard: 'Tourism Malaysia',
    insurance: 'Allianz Malaysia',
    esim: 'Maxis eSIM',
    visa: 'MDAC / e-Visa Malaisie',
    schengen: false,
  },
  {
    name: 'Singapour',
    capital: 'Singapour',
    airline: 'Singapore Airlines',
    rail: 'MRT Singapour',
    transfer: 'Changi Airport Shuttle',
    carRental: 'Budget Singapour',
    dmc: 'Local DMC Singapour',
    tourismBoard: 'Visit Singapore',
    insurance: 'Great Eastern',
    esim: 'Singtel eSIM',
    visa: 'SG Arrival Card',
    mice: 'Marina Bay Sands Expo',
    schengen: false,
  },
  {
    name: 'Philippines',
    capital: 'Manille',
    airline: 'Philippine Airlines',
    ferry: '2GO Travel',
    transfer: 'NAIA Airport Taxi',
    carRental: 'Budget Philippines',
    dmc: 'Local DMC Philippines',
    tourismBoard: 'Tourism Philippines',
    insurance: 'Malayan Insurance',
    esim: 'Globe eSIM',
    visa: 'e-Visa Philippines',
    schengen: false,
  },
  {
    name: 'Pakistan',
    capital: 'Islamabad',
    airline: 'PIA',
    rail: 'Pakistan Railways',
    transfer: 'Islamabad Airport Taxi',
    carRental: 'Budget Pakistan',
    dmc: 'Local DMC Pakistan',
    tourismBoard: 'Pakistan Tourism',
    insurance: 'EFU Life',
    esim: 'Jazz eSIM',
    visa: 'e-Visa Pakistan',
    schengen: false,
  },
  {
    name: 'Sri Lanka',
    capital: 'Colombo',
    airline: 'SriLankan Airlines',
    rail: 'Sri Lanka Railways',
    transfer: 'Colombo Airport Taxi',
    carRental: 'Budget Sri Lanka',
    dmc: 'Local DMC Sri Lanka',
    tourismBoard: 'Sri Lanka Tourism',
    insurance: 'Ceylinco Insurance',
    esim: 'Dialog eSIM',
    visa: 'e-Visa Sri Lanka',
    schengen: false,
  },
  {
    name: 'Cambodge',
    capital: 'Phnom Penh',
    airline: 'Cambodia Angkor Air',
    transfer: 'Phnom Penh Airport Taxi',
    carRental: 'Budget Cambodge',
    dmc: 'Local DMC Cambodge',
    tourismBoard: 'Tourism Cambodia',
    insurance: 'Fortune General',
    esim: 'Cellcard eSIM',
    visa: 'e-Visa Cambodge',
    schengen: false,
  },
  {
    name: 'Népal',
    capital: 'Katmandou',
    airline: 'Nepal Airlines',
    transfer: 'Tribhuvan Airport Taxi',
    carRental: 'Local car rental Népal',
    dmc: 'Local DMC Népal',
    tourismBoard: 'Nepal Tourism Board',
    insurance: 'Nepal Insurance',
    esim: 'Ncell eSIM',
    visa: 'e-Visa Népal',
    schengen: false,
  },
  {
    name: 'Kazakhstan',
    capital: 'Astana',
    airline: 'Air Astana',
    rail: 'KTZ',
    transfer: 'Astana Airport Taxi',
    carRental: 'Budget Kazakhstan',
    dmc: 'Local DMC Kazakhstan',
    tourismBoard: 'Kazakhstan Tourism',
    insurance: 'Halyk Insurance',
    esim: 'Beeline KZ eSIM',
    visa: 'e-Visa Kazakhstan',
    schengen: false,
  },
  {
    name: 'Ouzbékistan',
    capital: 'Tachkent',
    airline: 'Uzbekistan Airways',
    rail: 'Uzbekistan Railways',
    transfer: 'Tachkent Metro Airport',
    carRental: 'Local car rental Ouzbékistan',
    dmc: 'Local DMC Ouzbékistan',
    tourismBoard: 'Uzbekistan Tourism',
    esim: 'Beeline UZ eSIM',
    visa: 'e-Visa Ouzbékistan',
    schengen: false,
  },
  {
    name: 'Géorgie',
    capital: 'Tbilissi',
    airline: 'Georgian Airways',
    rail: 'Georgian Railway',
    transfer: 'Tbilisi Airport Taxi',
    carRental: 'Budget Géorgie',
    dmc: 'Local DMC Géorgie',
    tourismBoard: 'Georgia Travel',
    esim: 'Magti eSIM',
    visa: 'e-Visa Géorgie',
    schengen: false,
  },
  {
    name: 'Arménie',
    capital: 'Erevan',
    airline: 'FlyOne Armenia',
    transfer: 'Yerevan Airport Taxi',
    carRental: 'Local car rental Arménie',
    dmc: 'Local DMC Arménie',
    tourismBoard: 'Armenia Travel',
    esim: 'VivaCell eSIM',
    visa: 'e-Visa Arménie',
    schengen: false,
  },
  {
    name: 'Azerbaïdjan',
    capital: 'Bakou',
    airline: 'AZAL',
    rail: 'ADY',
    transfer: 'Baku Airport Taxi',
    carRental: 'Budget Azerbaïdjan',
    dmc: 'Local DMC Azerbaïdjan',
    tourismBoard: 'Azerbaijan Tourism',
    esim: 'Azercell eSIM',
    visa: 'e-Visa Azerbaïdjan',
    schengen: false,
  },
]

/** @type {CountryProfile[]} */
export const LATAM_PROFILES = [
  {
    name: 'Mexique',
    capital: 'Mexico',
    airline: 'Aeroméxico',
    rail: 'Ferromex / Chepe',
    transfer: 'CDMX Airport Metrobus',
    carRental: 'Europcar Mexique',
    dmc: 'Local DMC Mexique',
    tourismBoard: 'Visit Mexico',
    insurance: 'GNP Seguros',
    esim: 'Telcel eSIM',
    visa: 'e-Visa Mexique / FMM',
    mice: 'Centro Citibanamex',
    schengen: false,
  },
  {
    name: 'Brésil',
    capital: 'São Paulo',
    airline: 'LATAM Brasil',
    transfer: 'GRU Airport Transfer',
    carRental: 'Localiza',
    dmc: 'Local DMC Brésil',
    tourismBoard: 'Visit Brasil',
    insurance: 'Porto Seguro',
    esim: 'Vivo eSIM',
    visa: 'e-Visa Brésil',
    mice: 'Expo Center Norte',
    schengen: false,
  },
  {
    name: 'Argentine',
    capital: 'Buenos Aires',
    airline: 'Aerolíneas Argentinas',
    rail: 'Trenes Argentinos',
    ferry: 'Buquebus',
    transfer: 'Ezeiza Airport Taxi',
    carRental: 'Hertz Argentine',
    dmc: 'Local DMC Argentine',
    tourismBoard: 'Argentina Travel',
    insurance: 'La Caja Seguros',
    esim: 'Claro AR eSIM',
    visa: 'e-Visa Argentine',
    schengen: false,
  },
  {
    name: 'Colombie',
    capital: 'Bogotá',
    airline: 'Avianca',
    transfer: 'TransMilenio Bogotá',
    carRental: 'Budget Colombie',
    dmc: 'Local DMC Colombie',
    tourismBoard: 'Colombia Travel',
    insurance: 'Sura Colombie',
    esim: 'Claro CO eSIM',
    visa: 'Check-MIG Colombie',
    schengen: false,
  },
  {
    name: 'Chili',
    capital: 'Santiago',
    airline: 'LATAM Chile',
    transfer: 'Santiago Airport Transfer',
    carRental: 'Europcar Chili',
    dmc: 'Local DMC Chili',
    tourismBoard: 'Chile Travel',
    insurance: 'Consorcio Seguros',
    esim: 'Entel eSIM',
    visa: 'e-Visa Chili',
    schengen: false,
  },
  {
    name: 'Pérou',
    capital: 'Lima',
    airline: 'LATAM Perú',
    rail: 'Inca Rail',
    transfer: 'Lima Airport Express',
    carRental: 'Budget Pérou',
    dmc: 'Local DMC Pérou',
    tourismBoard: 'Peru Travel',
    insurance: 'Rimac Seguros',
    esim: 'Movistar PE eSIM',
    visa: 'e-Visa Pérou',
    schengen: false,
  },
  {
    name: 'Uruguay',
    capital: 'Montevideo',
    airline: 'LATAM Uruguay',
    ferry: 'Buquebus Uruguay',
    transfer: 'Montevideo Airport Taxi',
    carRental: 'Budget Uruguay',
    dmc: 'Local DMC Uruguay',
    tourismBoard: 'Uruguay Natural',
    insurance: 'BSE Seguros',
    esim: 'Antel eSIM',
    schengen: false,
  },
  {
    name: 'Équateur',
    capital: 'Quito',
    airline: 'Avianca Équateur',
    transfer: 'Quito Airport Taxi',
    carRental: 'Budget Équateur',
    dmc: 'Local DMC Équateur',
    tourismBoard: 'Ecuador Travel',
    insurance: 'Seguros Equinoccial',
    esim: 'Claro EC eSIM',
    visa: 'e-Visa Équateur',
    schengen: false,
  },
  {
    name: 'Panama',
    capital: 'Panama',
    airline: 'Copa Airlines',
    transfer: 'Metro Panama',
    carRental: 'Budget Panama',
    dmc: 'Local DMC Panama',
    tourismBoard: 'Visit Panama',
    insurance: 'Assa Compañía',
    esim: 'Movistar PA eSIM',
    mice: 'Atlapa Convention Center',
    schengen: false,
  },
  {
    name: 'Costa Rica',
    capital: 'San José',
    airline: 'Avianca Costa Rica',
    transfer: 'SJO Airport Shuttle',
    carRental: 'Budget Costa Rica',
    dmc: 'Local DMC Costa Rica',
    tourismBoard: 'Visit Costa Rica',
    insurance: 'INS Costa Rica',
    esim: 'Kölbi eSIM',
    schengen: false,
  },
  {
    name: 'Cuba',
    capital: 'La Havane',
    airline: 'Cubana de Aviación',
    transfer: 'Havana Airport Taxi',
    carRental: 'Havanautos',
    dmc: 'Local DMC Cuba',
    tourismBoard: 'Cuba Travel',
    insurance: 'Esicuba',
    esim: 'Cubacel eSIM',
    visa: 'Tarjeta del Turista Cuba',
    schengen: false,
  },
  {
    name: 'République dominicaine',
    capital: 'Saint-Domingue',
    airline: 'Arajet',
    transfer: 'SDQ Airport Taxi',
    carRental: 'Budget RD',
    dmc: 'Local DMC République dominicaine',
    tourismBoard: 'Go Dominican Republic',
    insurance: 'Seguros Universal',
    esim: 'Claro DO eSIM',
    visa: 'Tarjeta touristique RD',
    schengen: false,
  },
  {
    name: 'Bolivie',
    capital: 'La Paz',
    airline: 'Boliviana de Aviación',
    transfer: 'El Alto Airport Taxi',
    carRental: 'Local car rental Bolivie',
    dmc: 'Local DMC Bolivie',
    tourismBoard: 'Bolivia Travel',
    esim: 'Entel BO eSIM',
    visa: 'e-Visa Bolivie',
    schengen: false,
  },
  {
    name: 'Paraguay',
    capital: 'Asunción',
    airline: 'LATAM Paraguay',
    transfer: 'Asunción Airport Taxi',
    carRental: 'Budget Paraguay',
    dmc: 'Local DMC Paraguay',
    tourismBoard: 'Paraguay Travel',
    esim: 'Tigo PY eSIM',
    schengen: false,
  },
  {
    name: 'Venezuela',
    capital: 'Caracas',
    airline: 'Conviasa',
    transfer: 'Caracas Airport Taxi',
    carRental: 'Local car rental Venezuela',
    dmc: 'Local DMC Venezuela',
    tourismBoard: 'Venezuela Travel',
    esim: 'Movistar VE eSIM',
    visa: 'Visa Venezuela — consulat',
    schengen: false,
  },
  {
    name: 'Guatemala',
    capital: 'Guatemala',
    airline: 'Avianca Guatemala',
    transfer: 'GUA Airport Shuttle',
    carRental: 'Budget Guatemala',
    dmc: 'Local DMC Guatemala',
    tourismBoard: 'Visit Guatemala',
    esim: 'Claro GT eSIM',
    schengen: false,
  },
]

/** Profils générés — hors pays déjà détaillés manuellement. */
export const EXTENDED_COUNTRY_PROFILES = [
  ...EU_COUNTRY_PROFILES,
  ...GULF_MENA_PROFILES,
  ...ASIA_PROFILES,
  ...LATAM_PROFILES,
  ...AFRICA_COUNTRY_PROFILES,
]

/** Pays déjà définis manuellement (priorité sur le générateur). */
export const HAND_CRAFTED_COUNTRIES = new Set([
  'Maroc',
  'Algérie',
  'Tunisie',
  'France',
  'Espagne',
  'Portugal',
  'Italie',
  'Belgique',
  'Suisse',
  'Royaume-Uni',
  'Turquie',
  'Égypte',
  'Émirats arabes unis',
  'Sénégal',
])

export const EXTENDED_COUNTRY_PROFILES_TO_BUILD = EXTENDED_COUNTRY_PROFILES.filter(
  p => !HAND_CRAFTED_COUNTRIES.has(p.name),
)
